# Generated by Django 3.0.5 on 2021-01-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('county', models.CharField(max_length=64)),
                ('phone_no', models.CharField(max_length=64, unique=True)),
                ('id_no', models.CharField(max_length=64, unique=True)),
                ('uniqid', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
