# Generated by Django 3.0.5 on 2021-01-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_farmers'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='uniqid',
            field=models.CharField(default='jjjj', max_length=12),
        ),
    ]
