# Generated by Django 3.0.5 on 2021-01-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_farmers_uniqid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmers',
        ),
    ]
