# Generated by Django 3.0.5 on 2021-01-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_delete_farmers'),
        ('Farmers', '0002_auto_20210125_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqid', models.CharField(default='uniqid_unset', max_length=12)),
                ('farmer_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_id', to='Farmers.Farmers')),
            ],
        ),
        migrations.AlterField(
            model_name='animals',
            name='breed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='breed_id', to='Farmers.Breeds'),
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('vet_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vet_id', to='officers.Officer')),
            ],
        ),
        migrations.CreateModel(
            name='Farmers_Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqid', models.CharField(default='uniqid_unset', max_length=12)),
                ('animal_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='animal_id', to='Farmers.Animals')),
                ('farm_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='farm_id', to='Farmers.Farm')),
            ],
        ),
    ]
