# Generated by Django 3.0.5 on 2021-01-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0004_visits_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='visit_date',
            field=models.DateTimeField(),
        ),
    ]
