# Generated by Django 3.0.5 on 2021-01-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0006_visits_farm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='farm_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='farm_identity', to='Farmers.Farm'),
        ),
    ]
